"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tree_store_1 = require("./utils/tree-store");
const data_1 = require("./data");
const ts = new tree_store_1.TreeStore(data_1.items);
console.log('Result of getAll(): ', ts.getAll());
console.log('Result of getItem(7): ', ts.getItem(7));
console.log('Result of ts.getChildren(4): ', ts.getChildren(4));
console.log('Result of ts.getChildren(5): ', ts.getChildren(5));
console.log('Result of ts.getChildren(2): ', ts.getChildren(2));
console.log('Result of ts.getAllChildren(2): ', ts.getAllChildren(2));
